name: mdi_plus
description: Material Design Icons for Flutter from the materialdesignicons.com community.
version: 7.0.1
repository: https://github.com/mamm26/flutter_mdi_plus

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: Material Design Icons
      fonts:
        - asset: fonts/materialdesignicons-webfont.ttf

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
